name: Build Docker image
description: Builds a Docker image from the code of the current commit

inputs:
  image-name:
    description: Name of the image
    required: true
    
  interdiscount-coop-user-pw:
    description: Coop user password to access private GitHub npm registry
    required: true

runs:
  using: composite
  steps:
    - name: Extract 
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${{ github.ref_name }} | tr / -)" >> $GITHUB_ENV

    - name: Build Docker image
      shell: bash
      run: |
        docker build \
        --build-arg NPM_TOKEN=${{ inputs.interdiscount-coop-user-pw }} \
        -t ghcr.io/interdiscount/${{ inputs.image-name }}:sha-${GITHUB_SHA::9} \
        -t ghcr.io/interdiscount/${{ inputs.image-name }}:${ env.BRANCH_NAME }-${GITHUB_SHA::9} \
        -t ghcr.io/interdiscount/${{ inputs.image-name }}:${ env.BRANCH_NAME }-latest \
        .
